/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js, but is committed here so the project can
// typecheck immediately after dependencies are installed.
